### ISSUE TITLE
Improve scan

### ISSUE THREAD

**Issue by KordonDev** [jf-landkreis-karlsruhe/lager-melder#211]
- [x] Move camera scan preview to bottom of view, move input up
- [x] After scanning focus should stay in input or focus on input not needed

A scan from the scanner always sends an <Enter> at the end and codes are eg.
```
atten101
atten202
atten302
```

**Comment by crymis** [comment]
Wanted to start... After pulling main and docker-compose down and run `run.sh` I get this error.

```
lm-backend   | [INFO] BUILD FAILURE
lm-backend   | [INFO] ------------------------------------------------------------------------
lm-backend   | [INFO] Total time:  40.928 s
lm-backend   | [INFO] Finished at: 2025-01-11T21:37:17Z
lm-backend   | [INFO] ------------------------------------------------------------------------
lm-backend   | [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.2.5:run (default-cli) on project lager-melder-backend: Process terminated with exit code: 1 -> [Help 1]
```

**Comment by KordonDev** [comment]
Works for me. Can you include more logs from the backend? 200 to 300 lines would be good. Maybe also make a `docker-compose -f ./backend/docker-compose/docker-compose.yml down` before you start. Is your port 8080 used by another application?

**Comment by crymis** [comment]
I already did docker-compose down. But I just tried again.

This is more of the error:
```
.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.DefaultListableBeanFactory$1.getIfUnique(DefaultListableBeanFactory.java:438) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.security.config.annotation.web.builders.WebSecurity.setApplicationContext(WebSecurity.java:397) ~[spring-security-config-6.2.4.jar:6.2.4]
lm-backend   |  at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:110) ~[spring-context-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:85) ~[spring-context-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:412) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor.initializeBeanIfNeeded(AutowireBeanFactoryObjectPostProcessor.java:98) ~[spring-security-config-6.2.4.jar:6.2.4]
lm-backend   |  at org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor.postProcess(AutowireBeanFactoryObjectPostProcessor.java:67) ~[spring-security-config-6.2.4.jar:6.2.4]
lm-backend   |  ... 23 common frames omitted
lm-backend   | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mvcHandlerMappingIntrospector' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Ambiguous mapping. Cannot map 'registerController' method 
lm-backend   | de.kordondev.lagermelder.rest.controller.RegisterController#addDepartmentAndUser(RestDepartmentWithUserRequest)
lm-backend   | to {POST [/register]}: There is already 'authorizationController' bean method
lm-backend   | de.kordondev.lagermelder.rest.controller.AuthorizationController#addDepartmentAndUser(RestDepartmentWithUserRequest) mapped.
lm-backend   |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:365) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  ... 46 common frames omitted
lm-backend   | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Ambiguous mapping. Cannot map 'registerController' method 
lm-backend   | de.kordondev.lagermelder.rest.controller.RegisterController#addDepartmentAndUser(RestDepartmentWithUserRequest)
lm-backend   | to {POST [/register]}: There is already 'authorizationController' bean method
lm-backend   | de.kordondev.lagermelder.rest.controller.AuthorizationController#addDepartmentAndUser(RestDepartmentWithUserRequest) mapped.
lm-backend   |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:665) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1388) ~[spring-context-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.BeanFactoryUtils.beansOfTypeIncludingAncestors(BeanFactoryUtils.java:368) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.web.servlet.handler.HandlerMappingIntrospector.initHandlerMappings(HandlerMappingIntrospector.java:130) ~[spring-webmvc-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.web.servlet.handler.HandlerMappingIntrospector.afterPropertiesSet(HandlerMappingIntrospector.java:118) ~[spring-webmvc-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1833) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  ... 53 common frames omitted
lm-backend   | Caused by: java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'registerController' method 
lm-backend   | de.kordondev.lagermelder.rest.controller.RegisterController#addDepartmentAndUser(RestDepartmentWithUserRequest)
lm-backend   | to {POST [/register]}: There is already 'authorizationController' bean method
lm-backend   | de.kordondev.lagermelder.rest.controller.AuthorizationController#addDepartmentAndUser(RestDepartmentWithUserRequest) mapped.
lm-backend   |  at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$MappingRegistry.validateMethodMapping(AbstractHandlerMethodMapping.java:674) ~[spring-webmvc-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$MappingRegistry.register(AbstractHandlerMethodMapping.java:636) ~[spring-webmvc-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.registerHandlerMethod(AbstractHandlerMethodMapping.java:331) ~[spring-webmvc-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.registerHandlerMethod(RequestMappingHandlerMapping.java:508) ~[spring-webmvc-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.registerHandlerMethod(RequestMappingHandlerMapping.java:84) ~[spring-webmvc-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.lambda$detectHandlerMethods$2(AbstractHandlerMethodMapping.java:298) ~[spring-webmvc-6.1.6.jar:6.1.6]
lm-backend   |  at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986) ~[na:na]
lm-backend   |  at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.detectHandlerMethods(AbstractHandlerMethodMapping.java:296) ~[spring-webmvc-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.processCandidateBean(AbstractHandlerMethodMapping.java:265) ~[spring-webmvc-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:224) ~[spring-webmvc-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:212) ~[spring-webmvc-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:239) ~[spring-webmvc-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1833) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-6.1.6.jar:6.1.6]
lm-backend   |  ... 66 common frames omitted
lm-backend   | 
lm-backend   | [INFO] ------------------------------------------------------------------------
lm-backend   | [INFO] BUILD FAILURE
lm-backend   | [INFO] ------------------------------------------------------------------------
lm-backend   | [INFO] Total time:  38.472 s
lm-backend   | [INFO] Finished at: 2025-01-12T09:57:17Z
lm-backend   | [INFO] ------------------------------------------------------------------------
lm-backend   | [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.2.5:run (default-cli) on project lager-melder-backend: Process terminated with exit code: 1 -> [Help 1]
lm-backend   | [ERROR] 
lm-backend   | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
lm-backend   | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
lm-backend   | [ERROR] 
lm-backend   | [ERROR] For more information about the errors and possible solutions, please read the following articles:
lm-backend   | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
lm-backend exited with code 1
```
